# # # # # # # # # # # # #
#   K i k o - p l u s   #
# # # # # # # # # # # # #

# Basic
name:               "christiansalvatore"



author:
  name:             Christian Salvatore
  #facebook:         your-id
  twitter:          cd_salvatore
  github:           christiansalvatore
  #linkedin:         your-id
  #medium:           your-id
  #tumblr:           your-id
  email:            christian.salvatore@ibfm.cnr.it

# Google-analytics
google-analytics:
  id:               "UA-85985571-1"

# Disqus
disqus:
  id:               "christiansalvatore"

# URL
url:                "https://christiansalvatore.github.io"
#url:               "localhost:4000"
baseurl:            "https://christiansalvatore.github.io"


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           Europe/Rome
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           5
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  imput:            GFM

# Navigation
nav:
#  - name:           "About"
#    url:            "/about"
  - name:           "Archive"
    url:            "/archive"
  - name:           "Tags"
    url:            "/tags"
  - name:           "Github"
    url:            "https://github.com/christiansalvatore"
  - name:           "Publications"
    url:            "/publications/publications-bibbase.html"    
  - name:           "Awards"
    url:            "/awards/awards.html"        
#  - name:           "Dissemination"
#    url:            "/dissemination/dissemination.html"        



# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
gems:
  - jekyll-seo-tag
  - jekyll-paginate

exclude:            [vendor]
